### ISSUE TITLE
add Token Verification (blue tick) & Token Black List

### ISSUE THREAD

**Issue by alchemlstcoin** [iotexproject/iotex-token-metadata#43]
Blue mark token verification could be added, to avoid fraud and scams with fake tokens.
And you could also add a black list to add the tokens that are not complying with the Iotex rules.

**Comment by raullenchai** [comment]
Definitely something worth considering - the hard part is who decides which tokens are fraud/scam/fake and which are legit? A decentralized way is to have ppl vote up/down a certain token on the page.

**Comment by alchemlstcoin** [comment]
Te explico, como por ejemplo ETH, USDT, BTC, WBTC y otros son tokens legítimos y son los más utilizados para estafar y hacer fraudes, ya con los tokens integrados en la cartera de Iopay, podrían firmarse, y los tokens creados para que se vea que el desarrollador quiere integrarlo a la familia XRC podrían firmarse.
Before merging the information and updating, it is verified that it is the original tokens.

Another idea is to create an IoX where it is integrated into the creation of the XCR20 tokens and the creators can pay a sum for their token and its commercialization.
